version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maillogdb
    ports:
      - "5433:5432"

  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    depends_on:
      - db
